language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

before_script:
  - go vet $(go list ./... | grep -v /vendor/)

script: 
  - GORACE="halt_on_error=1" go test -race -v $(go list ./... | grep -v /vendor/)